### ISSUE TITLE
Only activate hovered window when moving mouse?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [mattdavis90/overview-hover#1]
In MacOS, if you activate and then deactivate Mission Control without ever moving the mouse while MC is active, then it doesn't activate the hovered window. It only activates a new window if you actually move the mouse while MC is active. Would it be possible to implement this as an option?

**Comment by mattdavis90** [comment]
Hi, thanks for reporting this. I'd really like to add this functionality. I've had a branch locally for a while that tries to implement this and your other issue but I just can't get the timing correct and the documentation for Gnome Extensions is awful. I've pushed my work-in-progress branch up so others can see - maybe someone with greater knowledge of the Gnome Shell internals can help. Sorry

**Comment by mattdavis90** [comment]
I'd thought I'd add some extra context now I have a little more time. I'd initially hoped that I could track the hover state using either a mouse_move event or the overlay (the little close button and window label) events. The windowPreview never binds a mouse_move and I couldn't quite work out how to give it one so that was out. The overlay appears as soon as Overview mode is active annoyingly so that was also out. This meant using the mouse_enter and mouse_exit events. The issue here is that the mouse_enter fires as soon as the Overview shows and both events actually fire as the Overview transitions in and out of view. You can see my comment in the code where I track whether an animation or gesture is running. It's quite hacky and I wasn't particularly happy with it but it just about worked enough for my use case. The branch I pushed yesterday has some console logs showing when certain events fire in an attempt to find one that might help.

**Comment by DarwinAwardWinner** [comment]
Is it possible to record the mouse position when the overview first opens and then avoid switching windows if the mouse is in the exact same position when the overview exits? Technically this runs the risk that you could accidentally move the mouse away and then back to the exact pixel it started on and get the wrong behavior as a result, but in practice this risk is probably negligible (and could be further reduced by disabling this behavior after a "real" enter/exit event is triggered, since that unambiguously indicates mouse movement.

Another thought: when I activate the overview, if the initial mouse position is over a window, I see the overlap appear briefly and then immediately disappear. It seems to only reappear when another mouse enter event is triggered (see attached video). I don't know what happens at the code level, e.g. whether the mouse exit event is triggered when the overlay disappears, but I wonder if there's anything you can do with this?

[Screencast from 2024-02-04 07-32-08.webm](https://github.com/mattdavis90/overview-hover/assets/228145/94caa09e-8867-48e2-8503-d3801536f35e)

**Comment by mattdavis90** [comment]
I've just been having a play around with the hide/show overlay events and tracking gestures manually. This gets very close to the desired behaviour. The issue now is that the order of events aren't quite correct when closing the overlay. The hideOverlay event occurs just before the gestureBegin call so I lose track of the window you're hovering over - the same is true of the mouseLeave event. I feel like this is closer so I've pushed up the branch.

**Comment by mattdavis90** [comment]
I'm not 100% sure how to track the mouse position efficiently or how to bounds check whether the mouse is over a windowPreview - I might investigate if I can't find an event that triggers after the gestureBegin one.

**Comment by mattdavis90** [comment]
I've just pushed a version that I _think_ solves both issues. You have to move the mouse to activate the window and you must stay hovered over the preview while exiting Overview for it to have any effect.

There is still an issue though which is why I've not put this on the main branch yet and released - if your mouse is over a preview when you open Overview, then you have to fully leave the preview and come back over it to activate the change. This isn't consistent with Mac and I can't quite find a way to hook a mouseMove event on the preview but I feel like its close.

**Comment by mattdavis90** [comment]
You can try out the change btw by copying `extension.js` from the `fixes` branch and pasting it over the top of the currently installed extension (probably `~/.local/share/gnome-shell/extensions/overviewhover@mattdavis90/extension.js`) and then logging out and back in.

**Comment by mattdavis90** [comment]
I've updated the version on the `fixes` branch - I've added a mouse tracker. I _think_ it is fully working as expected. Are you able to test?

**Comment by DarwinAwardWinner** [comment]
In quick testing, the fixes branch seems to be working as I would want it to. No messing with the Z-order, and no switching the active window unless the mouse is moved while in overview.

**Comment by mattdavis90** [comment]
Great to hear. I'll keep testing tomorrow then do a release. I played some on multiple monitors and all seemed to work.

**Comment by mattdavis90** [comment]
The new version is now on the main branch and I've uploaded it to Gnome Extensions, pending review. Happy for me to close?

**Comment by DarwinAwardWinner** [comment]
Yeah, I'll update the extension on my laptop later tonight and let you know if anything unexpected happens, but I assume the actual code is the same as what I manually copied in.

**Comment by mattdavis90** [comment]
Yeh, functionally identical. I just tidied up some of the comments and got it ready to release. You may not see an update appear for a little while - the approval process for new versions can take a couple of days.

**Comment by mattdavis90** [comment]
That was quick. It's now live on gnome extensions
